// Prevents additional console window on Windows in release
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod disk;
mod flash;
mod github;
mod overlay;

use disk::DiskInfo;
use github::{DownloadResult, ReleaseInfo};
use tauri::Manager;
use tauri_plugin_updater::UpdaterExt;

/// Returns the OS locale (e.g. "pt-BR", "en-US") for i18n.
#[tauri::command]
fn get_locale() -> String {
    sys_locale::get_locale().unwrap_or_else(|| "en".to_string())
}

#[tauri::command]
fn get_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

#[tauri::command]
fn list_disks() -> Vec<DiskInfo> {
    disk::list_removable_disks()
}

#[tauri::command]
async fn check_latest_release(variant: String) -> Result<ReleaseInfo, String> {
    github::get_latest_release(&variant).await
}

/// Download the latest image to local cache (or return cached path).
#[tauri::command]
async fn download_image(app: tauri::AppHandle, variant: String) -> Result<DownloadResult, String> {
    let release = github::get_latest_release(&variant).await?;

    let cache_dir = app.path().app_cache_dir()
        .map_err(|e| format!("Cache dir error: {}", e))?;

    let (path, cached) = github::download_image(&app, &release, &cache_dir).await?;

    Ok(DownloadResult {
        path: path.to_string_lossy().to_string(),
        version: release.version,
        image_name: release.image_name,
        cached,
    })
}

/// Verify integrity of a local image file by computing its SHA256.
/// If expected_hash is provided, compares against it.
#[tauri::command]
async fn verify_image(
    app: tauri::AppHandle,
    image_path: String,
    expected_hash: Option<String>,
) -> Result<String, String> {
    let path = std::path::Path::new(&image_path);
    if !path.exists() {
        return Err("Image file not found".into());
    }

    let app_clone = app.clone();
    let path_clone = image_path.clone();
    let hash = tokio::task::spawn_blocking(move || {
        github::verify_sha256_with_progress(&app_clone, std::path::Path::new(&path_clone))
    }).await
        .map_err(|e| format!("Task error: {}", e))??;

    if let Some(expected) = expected_hash {
        if hash != expected {
            return Err(format!(
                "SHA256 mismatch\nExpected: {}\nGot: {}",
                expected, hash
            ));
        }
    }

    Ok(hash)
}

/// Flash an image to the SD card with privilege escalation.
///
/// `overlay_path` is either an absolute path to a `mipi-panel.dtbo`
/// generated by the website (https://arch-r.io/overlay-generator) or an
/// empty string. Empty means "use the default overlay shipped in the
/// image": flash_image_privileged then leaves /flash/overlays/
/// untouched. When a path is provided, the file is copied verbatim
/// into /flash/overlays/mipi-panel.dtbo after the image is written.
///
/// The flasher no longer generates or customizes DTBOs in-process:
/// that responsibility lives entirely in the web generator. Keeping
/// this command thin removes a big chunk of optional code paths (DTB
/// parsing, panel lookup, panel_config patching) from the desktop
/// binary.
#[tauri::command]
async fn flash_image(
    app: tauri::AppHandle,
    image_path: String,
    device: String,
    overlay_path: String,
    variant: String,
    verify: bool,
) -> Result<String, String> {
    let app_clone = app.clone();

    // Cache dir lives on the user's data disk, not /tmp (which is OS
    // disk and often too small for a decompressed 4+ GB image).
    let cache_dir = app.path().app_cache_dir()
        .map_err(|e| format!("Cache dir error: {}", e))?;

    tokio::task::spawn_blocking(move || {
        // Validate the overlay path early so the user gets the error
        // before we touch the SD card. Empty path is the "skip" sentinel
        // and is allowed.
        let trimmed_overlay = overlay_path.trim();
        if !trimmed_overlay.is_empty() {
            let p = std::path::Path::new(trimmed_overlay);
            if !p.is_absolute() || !p.is_file() {
                return Err(format!(
                    "Overlay path must be an existing file: {}",
                    trimmed_overlay
                ));
            }
        }

        // Decompress .xz/.gz into a cached temp image so flash_image_
        // privileged can write it block-for-block. If the source archive
        // is newer than the cached decompression we invalidate the
        // cache before reusing it.
        let is_compressed = image_path.ends_with(".xz") || image_path.ends_with(".gz");
        let flash_image_path = if is_compressed {
            let _ = std::fs::create_dir_all(&cache_dir);
            let temp_img = cache_dir.join("archr-flash-temp.img");
            if temp_img.exists() {
                let stale = match (std::fs::metadata(&image_path), std::fs::metadata(&temp_img)) {
                    (Ok(src), Ok(cached)) => match (src.modified(), cached.modified()) {
                        (Ok(s), Ok(c)) => s > c,
                        _ => false,
                    },
                    _ => false,
                };
                if stale { let _ = std::fs::remove_file(&temp_img); }
            }
            if !temp_img.exists() {
                use std::io::{BufReader, Read, Write};
                let src_file = std::fs::File::open(&image_path)
                    .map_err(|e| format!("Cannot open image: {}", e))?;
                let mut dst_file = std::fs::File::create(&temp_img)
                    .map_err(|e| format!("Cannot create temp: {}", e))?;
                let mut buf = vec![0u8; 4 * 1024 * 1024];
                if image_path.ends_with(".xz") {
                    let mut decoder = xz2::read::XzDecoder::new(BufReader::new(src_file));
                    loop {
                        let n = decoder.read(&mut buf)
                            .map_err(|e| format!("Decompress error: {}", e))?;
                        if n == 0 { break; }
                        dst_file.write_all(&buf[..n])
                            .map_err(|e| format!("Write error: {}", e))?;
                    }
                } else {
                    let mut decoder = flate2::read::GzDecoder::new(BufReader::new(src_file));
                    loop {
                        let n = decoder.read(&mut buf)
                            .map_err(|e| format!("Decompress error: {}", e))?;
                        if n == 0 { break; }
                        dst_file.write_all(&buf[..n])
                            .map_err(|e| format!("Write error: {}", e))?;
                    }
                }
                dst_file.flush().map_err(|e| format!("Flush: {}", e))?;
            }
            temp_img.to_string_lossy().to_string()
        } else {
            image_path.clone()
        };

        flash::flash_image_privileged(
            &app_clone,
            &flash_image_path,
            &device,
            trimmed_overlay,
            &variant,
            verify,
        )?;

        if is_compressed {
            let _ = std::fs::remove_file(cache_dir.join("archr-flash-temp.img"));
        }

        Ok("Flash complete".into())
    })
    .await
    .map_err(|e| format!("Task error: {}", e))?
}

// ---- Overlay Tab Commands ----

#[tauri::command]
fn find_archr_sd() -> Vec<String> {
    overlay::find_archr_partitions()
}

#[tauri::command]
fn read_overlay(boot_path: &str) -> overlay::OverlayStatus {
    overlay::read_overlay_status(boot_path)
}

/// Apply a user-generated overlay (`mipi-panel.dtbo` from the web
/// generator) to an existing ArchR SD card. Replaces the file at
/// /flash/overlays/mipi-panel.dtbo verbatim; no customisation knobs:
/// the user is expected to have configured everything on the website.
#[tauri::command]
fn apply_custom_overlay(
    boot_path: &str,
    dtbo_path: &str,
) -> Result<String, String> {
    let boot = std::path::Path::new(boot_path);
    let source = std::path::Path::new(dtbo_path);
    let target = boot.join("overlays/mipi-panel.dtbo");

    if !source.exists() {
        return Err("Custom overlay file not found.".into());
    }

    std::fs::copy(source, &target)
        .map_err(|e| format!("Failed to copy overlay: {}", e))?;

    // fsync the file and parent directory
    if let Ok(f) = std::fs::File::open(&target) {
        let _ = f.sync_all();
    }
    if let Ok(d) = std::fs::File::open(target.parent().unwrap()) {
        let _ = d.sync_all();
    }

    Ok("Custom overlay applied.".into())
}

/// Check if a new version of the Flasher app is available.
///
/// Offline-safe: the updater builder runs with a tight timeout so a
/// missing network surfaces in a few seconds. The frontend wraps this
/// call in try/catch silently, so a failure here is fully invisible.
#[tauri::command]
async fn check_app_update(app: tauri::AppHandle) -> Result<Option<String>, String> {
    let update = app.updater_builder()
        .timeout(std::time::Duration::from_secs(8))
        .build()
        .map_err(|e| format!("{}", e))?
        .check()
        .await
        .map_err(|e| format!("{}", e))?;

    match update {
        Some(u) => Ok(Some(format!("{}|{}", u.version, u.body.unwrap_or_default()))),
        None => Ok(None),
    }
}

/// Download and install the app update, then restart.
#[tauri::command]
async fn install_app_update(app: tauri::AppHandle) -> Result<(), String> {
    let update = app.updater_builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| format!("{}", e))?
        .check()
        .await
        .map_err(|e| format!("{}", e))?;

    if let Some(update) = update {
        update.download_and_install(|_, _| {}, || {})
            .await
            .map_err(|e| format!("{}", e))?;
        app.restart();
    }

    Ok(())
}

fn main() {
    // WebKitGTK EGL workaround for AppImage on Wayland.
    // The AppImage bundles an older libwayland-client.so that conflicts with
    // the system Mesa driver, causing "Could not create default EGL display:
    // EGL_BAD_PARAMETER". Fix: preload the system's libwayland-client.so.
    // LD_PRELOAD must be set before process start, so we re-exec ourselves.
    #[cfg(target_os = "linux")]
    {
        if std::env::var("ARCHR_FLASHER_REEXEC").is_err()
            && std::env::var("APPIMAGE").is_ok()
        {
            let wayland_libs = [
                "/usr/lib/libwayland-client.so",
                "/usr/lib64/libwayland-client.so",
                "/usr/lib/x86_64-linux-gnu/libwayland-client.so",
            ];
            for lib in &wayland_libs {
                if std::path::Path::new(lib).exists() {
                    let current_preload = std::env::var("LD_PRELOAD").unwrap_or_default();
                    if !current_preload.contains("libwayland-client") {
                        let new_preload = if current_preload.is_empty() {
                            lib.to_string()
                        } else {
                            format!("{}:{}", lib, current_preload)
                        };
                        // SAFETY: this runs before any threads are spawned,
                        // and we immediately re-exec the process.
                        unsafe {
                            std::env::set_var("LD_PRELOAD", &new_preload);
                            std::env::set_var("ARCHR_FLASHER_REEXEC", "1");
                        }
                        use std::os::unix::process::CommandExt;
                        let exe = std::env::current_exe().expect("Cannot get exe path");
                        let args: Vec<String> = std::env::args().skip(1).collect();
                        let err = std::process::Command::new(&exe)
                            .args(&args)
                            .exec();
                        eprintln!("Re-exec failed: {}", err);
                    }
                    break;
                }
            }
        }
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_process::init())
        .setup(|app| {
            #[cfg(desktop)]
            app.handle().plugin(
                tauri_plugin_updater::Builder::new().build()
            )?;
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            get_locale,
            get_version,
            list_disks,
            check_latest_release,
            download_image,
            verify_image,
            flash_image,
            find_archr_sd,
            read_overlay,
            apply_custom_overlay,
            check_app_update,
            install_app_update,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}