use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct Panel {
    pub id: String,
    pub name: String,
    pub dtbo: String,
}

// Filenames mirror the MB-folder layout in
// distribution/config/archr-dts/{original,clone,soysauce}/<MB>/ — one DTBO
// per motherboard revision, generated by config/mipi-generator/generator.sh
// with spaces in folder names converted to underscores.

/// Original R36S panels (15 motherboard revisions).
const PANELS_ORIGINAL: &[(&str, &str, &str)] = &[
    ("HL_R36H_V20",       "HL R36H V20 (2024-05-18)",          "HL-R36H-V20_2024-05-18.dtbo"),
    ("HL_R36H_V21",       "HL R36H V21 (2024-11-18)",          "HL-R36H-V21_2024-11-18.dtbo"),
    ("R35S_V11",          "R35S V11 (2022-08-18)",             "R35S-V11_2022-08-18.dtbo"),
    ("R36S_PLUS_V20",     "R36S Plus V20 (2025-03-18)",        "R36S_Plus-V20_2025-03-18.dtbo"),
    ("R36S_V12_P0",       "R36S V12 Panel 0 (2023-08-18)",     "R36S-V12_2023-08-18_Panel_0.dtbo"),
    ("R36S_V12_P4",       "R36S V12 Panel 4 (2023-08-18)",     "R36S-V12_2023-08-18_Panel_4.dtbo"),
    ("R36S_V21_2550",     "R36S V21 2550 (2024-12-18)",        "R36S-V21_2024-12-18_2550.dtbo"),
    ("R36S_V21_2551",     "R36S V21 2551 (2024-12-18)",        "R36S-V21_2024-12-18_2551.dtbo"),
    ("R36S_V21_2552",     "R36S V21 2552 (2024-12-18)",        "R36S-V21_2024-12-18_2552.dtbo"),
    ("R36S_V22",          "R36S V22 (2024-12-18)",             "R36S-V22_2024-12-18.dtbo"),
    ("R36S_V30",          "R36S V30 (2025-11-18)",             "R36S-V30_2025-11-18.dtbo"),
    ("R36S_Y02_1127",     "R36S Y02 (2024-11-27)",             "R36S-Y02_2024-11-27.dtbo"),
    ("R36S_Y02_1218",     "R36S Y02 (2024-12-18)",             "R36S-Y02_2024-12-18.dtbo"),
    ("R36XX_V21",         "R36XX V21 (2024-12-18)",            "R36XX-V21_2024-12-18.dtbo"),
    ("RG36S_Y07",         "RG36S Y07 (2025-09-11)",            "RG36S-Y07_2025-09-11.dtbo"),
];

/// Clone R36S panels (18 motherboard revisions).
const PANELS_CLONE: &[(&str, &str, &str)] = &[
    ("G80C_V11_P8",       "G80C MB V1.1 Panel 8 (2025-03-19)",   "G80C-MB_V1.1-20250319_Panel_8.dtbo"),
    ("G80C_V11_P9",       "G80C MB V1.1 Panel 9 (2025-03-19)",   "G80C-MB_V1.1-20250319_Panel_9.dtbo"),
    ("G80CA_V12_0422_P8", "G80CA MB V1.2 Panel 8 (2025-04-22)",  "G80CA-MB_V1.2-20250422_Panel_8.dtbo"),
    ("G80CA_V12_0422_P9", "G80CA MB V1.2 Panel 9 (2025-04-22)",  "G80CA-MB_V1.2-20250422_Panel_9.dtbo"),
    ("G80CA_V12_0423_P8", "G80CA MB V1.2 Panel 8 (2025-04-23)",  "G80CA-MB_V1.2-20250423_Panel_8.dtbo"),
    ("G80CA_V12_0423_P9", "G80CA MB V1.2 Panel 9 (2025-04-23)",  "G80CA-MB_V1.2-20250423_Panel_9.dtbo"),
    ("G80CA_V13_P8",      "G80CA MB V1.3 Panel 8 (2025-12-12)",  "G80CA-MB_V1.3-20251212_Panel_8.dtbo"),
    ("G80D_V10_P8",       "G80D MB V1.0 Panel 8 (2025-06-09)",   "G80D-MB_V1.0-20250609_Panel_8.dtbo"),
    ("GR36_V11",          "GR36 MB V1.1 (2025-04-22)",           "GR36-MB_V1.1-20250422.dtbo"),
    ("R36S_V12_VAR1_P3A", "R36S V12 Variant 1 Panel 3 A",        "R36S-V12_2023-08-18_Variant_1_Panel_3_A.dtbo"),
    ("R36S_V12_VAR1_P8A", "R36S V12 Variant 1 Panel 8 A",        "R36S-V12_2023-08-18_Variant_1_Panel_8_A.dtbo"),
    ("R36S_V12_VAR2_P1",  "R36S V12 Variant 2 Panel 1",          "R36S-V12_2023-08-18_Variant_2_Panel_1.dtbo"),
    ("R36S_V12_VAR2_P1A", "R36S V12 Variant 2 Panel 1 A",        "R36S-V12_2023-08-18_Variant_2_Panel_1_A.dtbo"),
    ("R36S_V12_VAR3_P3",  "R36S V12 Variant 3 Panel 3",          "R36S-V12_2023-08-18_Variant_3_Panel_3.dtbo"),
    ("R36S_V12_VAR3_PA",  "R36S V12 Variant 3 Panel A",          "R36S-V12_2023-08-18_Variant_3_Panel_A.dtbo"),
    ("R36S_V20_2541",     "R36S V20 2541 (2025-05-18)",          "R36S-V20_2025-05-18_2541.dtbo"),
    ("R36S_V20_2548",     "R36S V20 2548 (2025-05-18)",          "R36S-V20_2025-05-18_2548.dtbo"),
    ("R36S_V20_2549",     "R36S V20 2549 (2025-05-18)",          "R36S-V20_2025-05-18_2549.dtbo"),
];

/// Soysauce R36S panels (10 Y3506 motherboard revisions).
/// DTBO paths include the "soysauce/" prefix because original images keep
/// the soysauce overlays in /overlays/soysauce/ on the boot partition.
const PANELS_SOYSAUCE: &[(&str, &str, &str)] = &[
    ("SS_V03_1104",      "Y3506 V03 (2024-11-04)",          "soysauce/Y3506_V03_20241104.dtbo"),
    ("SS_V03_1210_2507", "Y3506 V03 2507 (2024-12-10)",     "soysauce/Y3506_v03_20241210_2507.dtbo"),
    ("SS_V03_1210_2533", "Y3506 V03 2533 (2024-12-10)",     "soysauce/Y3506_v03_20241210_2533.dtbo"),
    ("SS_V03_0317",      "Y3506 V03 (2025-03-17)",          "soysauce/Y3506_V03_20250317.dtbo"),
    ("SS_V04_253x_P6",   "Y3506 V04 253x Panel 6",          "soysauce/Y3506_V04_20250529_253x_Panel_6.dtbo"),
    ("SS_V04_253x_P7",   "Y3506 V04 253x Panel 7",          "soysauce/Y3506_V04_20250529_253x_Panel_7.dtbo"),
    ("SS_V04_2548",      "Y3506 V04 2548 (2025-05-29)",     "soysauce/Y3506_V04_20250529_2548.dtbo"),
    ("SS_V04_2548_P2",   "Y3506 V04 2548 Panel 2",          "soysauce/Y3506_V04_20250529_2548_Panel_2.dtbo"),
    ("SS_V05_2551",      "Y3506 V05 2551 (2025-12-15)",     "soysauce/Y3506_V05_20251215_2551.dtbo"),
    ("SS_V05_2601",      "Y3506 V05 2601 (2025-12-15)",     "soysauce/Y3506_V05_20251215_2601.dtbo"),
];

pub fn get_panels(console: &str) -> Vec<Panel> {
    let source = match console {
        "original" => PANELS_ORIGINAL,
        "clone" => PANELS_CLONE,
        "soysauce" => PANELS_SOYSAUCE,
        _ => return vec![],
    };
    source.iter().map(|(id, name, dtbo)| Panel {
        id: id.to_string(),
        name: name.to_string(),
        dtbo: dtbo.to_string(),
    }).collect()
}
