// Arch R Flasher: Wizard Frontend
// Tauri 2 IPC: all backend calls go through invoke()

const $ = (id) => document.getElementById(id);
const invoke = window.__TAURI__?.core?.invoke || (async () => {});

// ---------------------------------------------------------------------------
// i18n
// ---------------------------------------------------------------------------
let lang = {};
const SUPPORTED_LOCALES = ['en', 'pt-BR', 'es', 'zh', 'ru'];

async function initI18n() {
  try {
    const osLocale = await invoke('get_locale');
    const normalized = (osLocale || 'en').replace('_', '-');
    let locale = SUPPORTED_LOCALES.find(l => normalized.startsWith(l));
    if (!locale) {
      const langPart = normalized.split('-')[0];
      locale = SUPPORTED_LOCALES.find(l => l.startsWith(langPart)) || 'en';
    }
    const resp = await fetch(`i18n/${locale}.json`);
    lang = await resp.json();
  } catch (_) {
    try { const r = await fetch('i18n/en.json'); lang = await r.json(); } catch (_) {}
  }
  applyI18n();
}

function t(key, rep) {
  let s = lang[key] || key;
  if (rep) for (const [k, v] of Object.entries(rep)) s = s.replace(`{${k}}`, v);
  return s;
}

function applyI18n() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const k = el.getAttribute('data-i18n');
    if (lang[k]) el.textContent = lang[k];
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const k = el.getAttribute('data-i18n-title');
    if (lang[k]) el.title = lang[k];
  });
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------
let mode = 'flash';  // 'flash' or 'overlay'
let currentStep = 0;
let busy = false;

// Flash state
let selectedConsole = null;
let selectedDisk = null;
let imagePath = null;
// User-picked overlay (mipi-panel.dtbo generated by the website).
// `flashOverlayPath` is the absolute path on disk; empty string means
// the user opted to skip and use whatever default overlay the image
// ships with.
let flashOverlayPath = '';
let flashOverlaySkip = false;
// Default on, like rpi-imager. The user can opt out by unchecking the
// "Verify after writing" box on the Flash step.
let verifyEnabled = true;

// Overlay-mode state (apply overlay to an existing ArchR SD card).
let overlayBootPath = null;
let ovlOverlayPath = '';

const FLASH_STEPS = ['console', 'image', 'overlay', 'disk', 'flash'];
const OVERLAY_STEPS = ['ovl-detect', 'ovl-overlay', 'ovl-apply'];

const STEP_TITLES = {
  'console': 'select_console', 'image': 'select_image',
  'overlay': 'step_overlay', 'disk': 'select_sd_title', 'flash': 'step_flash',
  'ovl-detect': 'overlay_sd', 'ovl-overlay': 'step_overlay',
  'ovl-apply': 'step_apply',
};

function getSteps() { return mode === 'flash' ? FLASH_STEPS : OVERLAY_STEPS; }
function getStepId() { return getSteps()[currentStep]; }

// ---------------------------------------------------------------------------
// Wizard navigation
// ---------------------------------------------------------------------------
function goToStep(idx) {
  const steps = getSteps();
  if (idx < 0 || idx >= steps.length) return;
  currentStep = idx;
  updateUI();
}

function nextStep() {
  const steps = getSteps();
  if (currentStep < steps.length - 1) {
    // Execute step-specific actions before advancing
    const stepId = getStepId();
    if (mode === 'flash') {
      if (stepId === 'overlay') refreshDisks();
      if (stepId === 'disk') onDiskReady();
    }
    if (mode === 'overlay') {
      if (stepId === 'ovl-overlay') buildOverlaySummary();
    }
    goToStep(currentStep + 1);
  }
}

function prevStep() {
  if (currentStep > 0) goToStep(currentStep - 1);
}

function updateUI() {
  const steps = getSteps();
  const stepId = getStepId();
  const stepsNav = mode === 'flash' ? 'steps-flash' : 'steps-overlay';

  // Update sidebar steps
  $('steps-flash').classList.toggle('hidden', mode !== 'flash');
  $('steps-overlay').classList.toggle('hidden', mode !== 'overlay');

  document.querySelectorAll(`#${stepsNav} .step`).forEach((el, i) => {
    el.classList.toggle('active', i === currentStep);
    el.classList.toggle('done', i < currentStep);
  });

  // Update main content
  document.querySelectorAll('.step-content').forEach(el => el.classList.remove('active'));
  const page = $('page-' + stepId);
  if (page) page.classList.add('active');

  // Update title
  const titleKey = STEP_TITLES[stepId] || stepId;
  $('step-title').textContent = t(titleKey);

  // Update nav buttons
  $('btn-back').classList.toggle('hidden', currentStep === 0);
  updateNextButton();

  // Mode tabs
  $('mode-flash').classList.toggle('active', mode === 'flash');
  $('mode-overlay').classList.toggle('active', mode === 'overlay');
}

function updateNextButton() {
  const stepId = getStepId();
  const btn = $('btn-next');

  if (mode === 'flash') {
    switch (stepId) {
      case 'console': btn.disabled = !selectedConsole; break;
      case 'image': btn.disabled = !imagePath; break;
      case 'overlay': btn.disabled = !(flashOverlayPath || flashOverlaySkip); break;
      case 'disk': btn.disabled = !selectedDisk; break;
      case 'flash':
        btn.textContent = t('flash');
        btn.disabled = busy;
        break;
      default: btn.disabled = false;
    }
  } else {
    switch (stepId) {
      case 'ovl-detect': btn.disabled = !overlayBootPath; break;
      case 'ovl-overlay': btn.disabled = !ovlOverlayPath; break;
      case 'ovl-apply':
        btn.textContent = t('overlay_apply');
        btn.disabled = busy;
        break;
      default: btn.disabled = false;
    }
  }

  // Last step: change button text
  const steps = getSteps();
  if (currentStep === steps.length - 1) {
    if (mode === 'flash') btn.textContent = t('flash') || 'FLASH';
    else btn.textContent = t('overlay_apply') || 'APPLY';
  } else {
    btn.textContent = t('next') || 'NEXT';
  }
}

// ---------------------------------------------------------------------------
// Mode switching
// ---------------------------------------------------------------------------
$('mode-flash').addEventListener('click', () => {
  if (busy) return;
  mode = 'flash';
  currentStep = 0;
  updateUI();
});

$('mode-overlay').addEventListener('click', () => {
  if (busy) return;
  mode = 'overlay';
  currentStep = 0;
  updateUI();
  refreshOverlaySD();
});

// ---------------------------------------------------------------------------
// Nav buttons
// ---------------------------------------------------------------------------
$('btn-back').addEventListener('click', () => { if (!busy) prevStep(); });

$('btn-next').addEventListener('click', () => {
  if (busy) return;
  const steps = getSteps();
  if (currentStep === steps.length - 1) {
    // Last step action
    if (mode === 'flash') showFlashConfirm();
    else applyOverlay();
  } else {
    nextStep();
  }
});

// ---------------------------------------------------------------------------
// Console selection (Flash step 1)
// ---------------------------------------------------------------------------
document.querySelectorAll('#page-console .card').forEach(card => {
  card.addEventListener('click', () => {
    if (busy) return;
    const console = card.dataset.console;
    const changed = selectedConsole !== console;
    selectedConsole = console;

    document.querySelectorAll('#page-console .card').forEach(c => c.classList.remove('active'));
    card.classList.add('active');

    if (changed) {
      imagePath = null;
      $('image-name').textContent = t('no_image');
      $('image-version').textContent = '';
      // Reset overlay pick when console changes (different variants
      // expect different DTBs and the user's previous selection might
      // no longer be appropriate).
      flashOverlayPath = '';
      flashOverlaySkip = false;
      const pickedLabel = $('overlay-picked-flash');
      if (pickedLabel) pickedLabel.textContent = t('no_overlay_picked');
      const skipBox = $('overlay-skip-flash');
      if (skipBox) skipBox.checked = false;
      checkLatestVersion(console);
    }

    updateNextButton();
  });
});

// ---------------------------------------------------------------------------
// Overlay file picker (Flash step 3)
// ---------------------------------------------------------------------------
async function pickOverlayDtbo() {
  try {
    const selected = await window.__TAURI__.dialog.open({
      filters: [{ name: 'Overlay (mipi-panel.dtbo)', extensions: ['dtbo'] }],
      multiple: false,
    });
    if (!selected) return null;
    return typeof selected === 'string' ? selected : (selected.path || selected);
  } catch (e) {
    setFlashStatus(t('error') + ': ' + e, 'error');
    return null;
  }
}

$('btn-pick-overlay-flash')?.addEventListener('click', async () => {
  if (busy) return;
  const picked = await pickOverlayDtbo();
  if (picked) {
    flashOverlayPath = String(picked);
    flashOverlaySkip = false;
    $('overlay-skip-flash').checked = false;
    $('overlay-picked-flash').textContent = flashOverlayPath.split(/[/\\]/).pop();
    updateNextButton();
  }
});

$('verify-toggle')?.addEventListener('change', (e) => {
  verifyEnabled = e.target.checked;
});

$('overlay-skip-flash')?.addEventListener('change', (e) => {
  flashOverlaySkip = e.target.checked;
  if (flashOverlaySkip) {
    flashOverlayPath = '';
    $('overlay-picked-flash').textContent = t('overlay_will_skip');
  } else if (!flashOverlayPath) {
    $('overlay-picked-flash').textContent = t('no_overlay_picked');
  }
  updateNextButton();
});

$('btn-pick-overlay-ovl')?.addEventListener('click', async () => {
  if (busy) return;
  const picked = await pickOverlayDtbo();
  if (picked) {
    ovlOverlayPath = String(picked);
    $('overlay-picked-ovl').textContent = ovlOverlayPath.split(/[/\\]/).pop();
    updateNextButton();
  }
});

// ---------------------------------------------------------------------------
// Latest version check
// ---------------------------------------------------------------------------
async function checkLatestVersion(console) {
  $('image-version').textContent = t('checking_version');
  try {
    const variant = console === 'soysauce' ? 'original' : console;
    const release = await invoke('check_latest_release', { variant });
    if (selectedConsole === console) {
      $('image-version').textContent = t('latest_version', { version: release.version });
    }
  } catch (_) {
    if (selectedConsole === console) $('image-version').textContent = t('offline');
  }
}

// ---------------------------------------------------------------------------
// Image selection
// ---------------------------------------------------------------------------
$('btn-select-file').addEventListener('click', async () => {
  if (busy) return;
  try {
    const selected = await window.__TAURI__.dialog.open({
      filters: [{ name: 'Arch R Image', extensions: ['img', 'xz', 'gz'] }]
    });
    if (selected) {
      imagePath = selected;
      $('image-name').textContent = selected.split(/[/\\]/).pop();
      $('image-name').style.color = 'var(--text)';
      $('image-version').textContent = '';
      updateNextButton();
    }
  } catch (e) { setFlashStatus(t('error') + ': ' + e, 'error'); }
});

$('btn-download').addEventListener('click', async () => {
  if (busy) return;
  setBusy(true);
  const dlProg = $('download-progress');
  dlProg.classList.remove('hidden');
  $('dl-progress-fill').style.width = '0%';
  $('dl-progress-text').textContent = '0%';

  try {
    // Soysauce uses original image
    const variant = selectedConsole === 'soysauce' ? 'original' : selectedConsole;
    const result = await invoke('download_image', { variant });
    imagePath = result.path;
    $('image-name').textContent = result.image_name;
    $('image-name').style.color = 'var(--text)';
    $('image-version').textContent = result.version;
    $('dl-progress-fill').style.width = '100%';
    $('dl-progress-text').textContent = '100%';
    setTimeout(() => dlProg.classList.add('hidden'), 2000);
  } catch (e) {
    setFlashStatus(translateError(e), 'error');
    dlProg.classList.add('hidden');
  }
  setBusy(false);
  updateNextButton();
});

window.__TAURI__?.event?.listen('download-progress', (event) => {
  const { percent, downloaded_bytes, total_bytes } = event.payload;
  $('dl-progress-fill').style.width = percent.toFixed(1) + '%';
  $('dl-progress-text').textContent = percent.toFixed(0) + '%';
});

// ---------------------------------------------------------------------------
// Disk selection (Flash step 5)
// ---------------------------------------------------------------------------
async function refreshDisks() {
  try {
    const disks = await invoke('list_disks');
    const sel = $('disk-select');
    sel.innerHTML = `<option value="">${t('select_sd')}</option>`;
    selectedDisk = null;
    disks.forEach(d => {
      const opt = document.createElement('option');
      opt.value = d.device;
      opt.textContent = d.name;
      sel.appendChild(opt);
    });
  } catch (_) {}
  updateNextButton();
}

$('disk-select').addEventListener('change', () => {
  selectedDisk = $('disk-select').value || null;
  updateNextButton();
});

$('btn-refresh-disks').addEventListener('click', refreshDisks);

function onDiskReady() { buildFlashSummary(); }

// ---------------------------------------------------------------------------
// Flash summary & execution
// ---------------------------------------------------------------------------
const CONSOLE_I18N = { original: 'original_name', clone: 'clone_name', soysauce: 'soysauce_name' };

function buildFlashSummary() {
  const consoleName = t(CONSOLE_I18N[selectedConsole] || selectedConsole);
  const overlayName = flashOverlayPath
    ? flashOverlayPath.split(/[/\\]/).pop()
    : t('overlay_default_image');
  const diskName = selectedDisk ? $('disk-select').options[$('disk-select').selectedIndex].textContent : t('overlay_none');
  const imgName = $('image-name').textContent;
  // Build via DOM API + textContent. Filenames picked by the user
  // (overlayName, imgName) may contain raw HTML metacharacters on
  // Linux/macOS, so concatenating them into innerHTML would be XSS
  // (even though the attack surface is self-XSS in a desktop app,
  // the safe pattern is cheap and worth keeping).
  const summary = $('flash-summary');
  summary.replaceChildren();
  const rows = [
    [t('step_console'), consoleName],
    [t('step_image'),   imgName],
    [t('step_overlay'), overlayName],
    [t('step_disk'),    diskName],
  ];
  for (const [label, value] of rows) {
    const strong = document.createElement('strong');
    strong.textContent = `${label}: `;
    summary.appendChild(strong);
    summary.appendChild(document.createTextNode(value));
    summary.appendChild(document.createElement('br'));
  }
}

function showFlashConfirm() {
  buildFlashSummary();
  const diskName = $('disk-select').options[$('disk-select').selectedIndex]?.textContent || selectedDisk;
  $('confirm-text').textContent = t('confirm_text', { disk: diskName });
  $('confirm-dialog').classList.remove('hidden');
}

$('btn-cancel').addEventListener('click', () => $('confirm-dialog').classList.add('hidden'));

$('btn-confirm').addEventListener('click', async () => {
  $('confirm-dialog').classList.add('hidden');
  await startFlash();
});

async function startFlash() {
  setBusy(true);
  $('flash-progress').classList.remove('hidden');
  $('progress-fill').style.width = '0%';
  $('progress-percent').textContent = '0%';
  $('progress-stage').textContent = t('writing');
  const sdWarn = $('sd-speed-warning');
  if (sdWarn) { sdWarn.classList.add('hidden'); sdWarn.textContent = ''; }
  setFlashStatus(t('writing'), '');

  try {
    // Empty overlayPath = user opted to skip; backend keeps whatever
    // mipi-panel.dtbo the image already carries (the default one
    // shipped in the build's /flash/overlays/ tree).
    await invoke('flash_image', {
      imagePath,
      device: selectedDisk,
      overlayPath: flashOverlayPath,
      variant: selectedConsole,
      verify: verifyEnabled,
    });
    $('progress-fill').style.width = '100%';
    $('progress-percent').textContent = '100%';
    $('progress-stage').textContent = '';
    setFlashStatus(t('done'), 'success');
  } catch (e) {
    const msg = typeof e === 'string' ? e : String(e);
    if (msg === 'cancelled') setFlashStatus(t('flash_cancelled'), '');
    else setFlashStatus(translateError(msg), 'error');
  }
  setBusy(false);
}

// Format bytes as MB or GB with 1 decimal. We intentionally use 1024
// (MiB/GiB) here because that's what dd writes and what users expect
// to see lining up with the SD card capacity printed on the box.
function formatBytes(n) {
  if (n == null || isNaN(n)) return '';
  const KB = 1024, MB = KB * 1024, GB = MB * 1024;
  if (n >= GB) return (n / GB).toFixed(2) + ' GB';
  if (n >= MB) return (n / MB).toFixed(0) + ' MB';
  if (n >= KB) return (n / KB).toFixed(0) + ' KB';
  return n + ' B';
}

window.__TAURI__?.event?.listen('flash-progress', (event) => {
  const { percent, stage, bytes_done, bytes_total } = event.payload;
  $('progress-fill').style.width = percent.toFixed(1) + '%';
  $('progress-percent').textContent = percent.toFixed(0) + '%';
  // Right of the bar: live MB / MB whenever the backend has a byte
  // counter (i.e. during writing and verifying). Falls back to the
  // stage label otherwise (decompressing, finalizing, etc.).
  if (bytes_total && bytes_total > 0) {
    $('progress-stage').textContent =
      formatBytes(bytes_done) + ' / ' + formatBytes(bytes_total);
  } else {
    $('progress-stage').textContent = t(stage) || stage;
  }
  // Below the bar: the human-readable phase ("Descompactando imagem...",
  // "Gravando imagem...", "Verificando integridade...", etc.) so the
  // user can see which phase the flasher is in even when the number
  // counter is the dominant element next to the bar.
  const phaseLabel = t(stage) || stage;
  if (phaseLabel) setFlashStatus(phaseLabel, '');
});

window.__TAURI__?.event?.listen('sd-speed-result', (event) => {
  const { quality, speed_mbs } = event.payload;
  const el = $('sd-speed-warning');
  if (!el) return;
  if (quality === 'slow') {
    el.textContent = t('sd_slow_warning').replace('{speed}', speed_mbs);
    el.className = 'sd-speed-warning sd-slow';
    el.classList.remove('hidden');
  } else if (quality === 'medium') {
    el.textContent = t('sd_medium_info').replace('{speed}', speed_mbs);
    el.className = 'sd-speed-warning sd-medium';
    el.classList.remove('hidden');
  } else {
    el.textContent = t('sd_fast_info').replace('{speed}', speed_mbs);
    el.className = 'sd-speed-warning sd-fast';
    el.classList.remove('hidden');
  }
});

// ---------------------------------------------------------------------------
// OVERLAY MODE
// ---------------------------------------------------------------------------

// Overlay: Detect SD (step 1)
async function refreshOverlaySD() {
  try {
    const parts = await invoke('find_archr_sd');
    const sel = $('overlay-sd-select');
    sel.innerHTML = '';
    overlayBootPath = null;

    if (parts.length === 0) {
      const opt = document.createElement('option');
      opt.value = '';
      opt.textContent = t('overlay_no_sd');
      opt.disabled = true;
      sel.appendChild(opt);
    } else {
      sel.innerHTML = `<option value="">${t('select_sd')}</option>`;
      parts.forEach(p => {
        const opt = document.createElement('option');
        opt.value = p; opt.textContent = p;
        sel.appendChild(opt);
      });
      if (parts.length === 1) {
        sel.value = parts[0];
        await onOverlaySDSelected(parts[0]);
      }
    }
  } catch (e) { setOverlayStatus(t('error') + ': ' + e, 'error'); }
  updateNextButton();
}

$('overlay-sd-select').addEventListener('change', async () => {
  const val = $('overlay-sd-select').value;
  if (val) await onOverlaySDSelected(val);
  else { overlayBootPath = null; $('overlay-current-info').classList.add('hidden'); }
  updateNextButton();
});

async function onOverlaySDSelected(bootPath) {
  overlayBootPath = bootPath;
  try {
    const s = await invoke('read_overlay', { bootPath });
    if (!s.has_archr) { setOverlayStatus(t('overlay_not_archr'), 'error'); return; }

    $('ovl-cur-name').textContent = s.current_panel_name || t('overlay_none');
    $('ovl-cur-variant').textContent = s.variant || t('overlay_none');
    $('overlay-current-info').classList.remove('hidden');

    setOverlayStatus('', '');
  } catch (e) { setOverlayStatus(t('error') + ': ' + e, 'error'); }
  updateNextButton();
}

$('btn-refresh-overlay-sd').addEventListener('click', refreshOverlaySD);

// Overlay-mode: apply the user-picked overlay file to the existing
// ArchR SD card. No customisation knobs: the user is expected to
// have generated the DTBO on the website with all the right options
// baked in, just like the flash path.
async function applyOverlay() {
  if (!overlayBootPath || !ovlOverlayPath) return;
  setBusy(true);
  setOverlayStatus(t('overlay_applying'), '');

  try {
    await invoke('apply_custom_overlay', {
      bootPath: overlayBootPath,
      dtboPath: ovlOverlayPath,
    });

    buildOverlaySummary();
    setOverlayStatus(t('overlay_applied'), 'success');
  } catch (e) { setOverlayStatus(t('error') + ': ' + e, 'error'); }
  setBusy(false);
}

function buildOverlaySummary() {
  // ovlOverlayPath is a user-picked filesystem path; the basename can
  // legitimately contain raw `<` / `>` on Linux/macOS, so build via
  // createElement + textContent instead of innerHTML interpolation.
  const overlayName = ovlOverlayPath
    ? ovlOverlayPath.split(/[/\\]/).pop()
    : t('overlay_none');
  const summary = $('overlay-summary');
  summary.replaceChildren();
  const strong = document.createElement('strong');
  strong.textContent = `${t('step_overlay')}: `;
  summary.appendChild(strong);
  summary.appendChild(document.createTextNode(overlayName));
}

// ---------------------------------------------------------------------------
// Open the online overlay generator
// ---------------------------------------------------------------------------
// The flasher no longer generates DTBOs locally: users go to
// https://arch-r.io/overlay-generator, run the generator with their
// vendor DTB, download mipi-panel.dtbo, and pick it through the
// file-picker step.
const OVERLAY_GENERATOR_URL = 'https://arch-r.io/overlay-generator/';

// Actually navigate to the generator (Tauri opener, else a new browser tab).
const openGeneratorUrl = async () => {
  try {
    if (window.__TAURI__?.opener?.openUrl) {
      await window.__TAURI__.opener.openUrl(OVERLAY_GENERATOR_URL);
    } else if (window.__TAURI__?.shell?.open) {
      await window.__TAURI__.shell.open(OVERLAY_GENERATOR_URL);
    } else {
      window.open(OVERLAY_GENERATOR_URL, '_blank', 'noopener');
    }
  } catch (e) {
    console.error('Could not open online generator URL:', e);
  }
};

// Clicking "Open Generator" first shows a warning: users MUST use the
// original vendor .dtb, not one from dArkOS / ArkOS / clones. Only after
// acknowledging do we open the generator site.
const showGeneratorWarning = (ev) => {
  if (ev) ev.preventDefault();
  $('generator-warn-dialog').classList.remove('hidden');
};
$('btn-open-generator-flash')?.addEventListener('click', showGeneratorWarning);
$('btn-open-generator-ovl')?.addEventListener('click', showGeneratorWarning);
$('btn-generator-cancel')?.addEventListener('click', () => {
  $('generator-warn-dialog').classList.add('hidden');
});
$('btn-generator-ack')?.addEventListener('click', async () => {
  $('generator-warn-dialog').classList.add('hidden');
  await openGeneratorUrl();
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function setBusy(b) {
  busy = b;
  updateNextButton();
  document.querySelectorAll('.mode-tab').forEach(t => t.disabled = b);
}

function setFlashStatus(text, type) {
  $('flash-status').textContent = text;
  $('flash-status').className = 'status' + (type ? ' ' + type : '');
}

function setOverlayStatus(text, type) {
  $('overlay-status').textContent = text;
  $('overlay-status').className = 'status' + (type ? ' ' + type : '');
}

function formatBytes(bytes) {
  if (bytes >= 1e9) return (bytes / 1e9).toFixed(1) + ' GB';
  if (bytes >= 1e6) return (bytes / 1e6).toFixed(0) + ' MB';
  return bytes + ' B';
}

function translateError(msg) {
  if (typeof msg !== 'string') msg = String(msg);
  const patterns = [
    [/cancelled|canceled/i, 'flash_cancelled'],
    [/not enough temp space/i, 'error_no_space'],
    [/device not found|was the sd card removed/i, 'error_device_removed'],
    [/not a removable/i, 'error_not_removable'],
    [/no.*image.*found/i, 'error_no_image'],
    [/^offline:|network|dns|connect|timeout|reqwest::Error|tcp.*reset/i, 'error_network'],
    [/checksum.*fail|sha256 mismatch/i, 'error_checksum_failed'],
    [/verify_failed/i, 'error_verify_failed'],
    // Stable tokens from the native Windows writer (flash_windows.rs).
    [/err:write_protected/i, 'error_write_protected'],
    [/err:device_busy/i, 'error_device_busy'],
    [/err:media/i, 'error_media'],
    [/err:open_device/i, 'error_open_device'],
    [/err:dd_write|err:write_failed/i, 'error_write_failed'],
    [/err:mount_boot/i, 'error_mount_boot'],
    [/failed to run pkexec|osascript error|failed to run powershell|failed to run authopen/i, 'error_privilege'],
    [/not authorized|dismissed/i, 'error_privilege'],
    [/decompress error|xzdecoder/i, 'error_decompress'],
    [/write error|flush error/i, 'error_write_failed'],
    [/cannot open image/i, 'error_open_image'],
    [/cannot write helper|cannot set script|cannot write params|cannot create temp/i, 'error_prepare_flash'],
    [/dd error:/i, null],
    [/flash failed/i, 'error_flash_failed'],
    [/invalid device|invalid disk/i, 'error_invalid_device'],
  ];
  for (const [regex, key] of patterns) {
    if (regex.test(msg)) { if (key === null) break; return t(key); }
  }
  return t('error') + ': ' + msg;
}

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------
async function init() {
  await initI18n();
  updateUI();

  // Show app version
  try {
    const version = await invoke('get_version');
    if (version) $('app-version').textContent = 'v' + version;
  } catch (_) {}

  try {
    const result = await invoke('check_app_update');
    if (result) {
      const [version] = result.split('|');
      const yes = await window.__TAURI__.dialog.ask(
        t('app_update_text', { version }), { title: t('app_update_title'), kind: 'info' }
      );
      if (yes) { setFlashStatus(t('app_updating'), ''); await invoke('install_app_update'); }
    }
  } catch (_) {}
}

init();
